### PR TITLE
Update Jekyll to version 3.6

### LINKED ISSUE #85: Update Jekyll to 3.6

### PR DESCRIPTION
**Pull request by carolkng**
fixes #85

### CODE REVIEW

**Comment by nirgn975** [comment]
@carolkng Thanks a lot!! 👍 
Will you be able to change the [README.md](https://github.com/nirgn975/generator-jekyll-starter-kit/blob/master/generators/app/templates/my-awesome-site/README.md) file to install jekyll 3.6.0 and not 3.5.1, so I'll be able to merge this?

**Comment by carolkng** [comment]
Done! :+1:

**Comment by nirgn975** [comment]
@carolkng thank you so much for your contribution, happy Hacktoberfest! (:

**Comment by carolkng** [comment]
no problem, thank you for sharing the project on hacktoberfest 😄

**Pull request merged**
